name: Jamie's Blog
description: Trying to explain things I think I know
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

url: "https://jamiepollock.github.io"
baseurl: ""

codeUrl: "https://github.com/jamiepollock"

sass:
    sass_dir: _sass
    style: compressed